#!/usr/bin/env python3
"""Regenerate the generated sections of research.html.

Sources:
    publications.json -> the Publications list and its filter buttons
    software.json     -> the Software list (or its placeholder, while empty)

Adding a paper or a tool should be one JSON object, not forty lines of markup.
Output is written straight into research.html between the BUILD markers, so the
deployed page stays static HTML -- crawlers, Google Scholar and no-JS visitors
still see every entry.

    python3 build_research.py

Run it after every edit to publications.json or software.json.
"""

import html
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).parent
PUBS = ROOT / "publications.json"
SOFT = ROOT / "software.json"
PAGE = ROOT / "research.html"

LIST_START = "<!-- BUILD:publications-list start -- generated by build_research.py -->"
LIST_END = "<!-- BUILD:publications-list end -->"
FILTERS_START = "<!-- BUILD:publication-filters start -- generated by build_research.py -->"
FILTERS_END = "<!-- BUILD:publication-filters end -->"
SOFT_START = "<!-- BUILD:software start -- generated by build_research.py from software.json -->"
SOFT_END = "<!-- BUILD:software end -->"
UPDATED_START = "<!-- BUILD:last-updated start -->"
UPDATED_END = "<!-- BUILD:last-updated end -->"

ICON = '<svg class="icon" aria-hidden="true" focusable="false"><use href="#i-%s"></use></svg>'


def esc(text):
    """Escape text that must not be read as markup."""
    return html.escape(text, quote=True)


def render_item(pub, indent="                        "):
    i = indent
    badge = pub.get("badge") or {
        "journal": "Journal Article",
        "conference": "Conference Paper",
        "working": "Working Paper",
    }.get(pub["type"], pub["type"].title())

    out = []
    out.append(f'{i}<div class="publication-item" data-type="{esc(pub["type"])}" data-year="{pub["year"]}">')
    out.append(f'{i}    <div class="pub-cover">')
    out.append(
        f'{i}        <img src="images/journal-covers/{esc(pub["cover"])}"'
        f' alt="{esc(pub.get("cover_alt") or pub["venue"])}"'
        f' class="journal-cover" width="200" height="267" loading="lazy" decoding="async"'
        f' onerror="this.src=\'images/journal-covers/default-journal.webp\'">'
    )
    out.append(f'{i}    </div>')
    out.append(f'{i}    <div class="pub-content">')
    out.append(f'{i}        <div class="pub-title-row">')
    out.append(f'{i}            <h3 class="pub-title">{esc(pub["title"])}</h3>')
    out.append(f'{i}            <div class="pub-badges">')
    out.append(f'{i}                <span class="pub-type-badge {esc(pub["type"])}">{esc(badge)}</span>')
    out.append(f'{i}            </div>')
    out.append(f'{i}        </div>')
    # authors is trusted markup: it carries <strong> around his own name
    out.append(f'{i}        <p class="pub-authors">{pub["authors"]}</p>')
    out.append(f'{i}        <div class="pub-venue-info">')
    out.append(f'{i}            <span class="pub-venue">{esc(pub["venue"])}</span>')
    out.append(f'{i}            <span class="pub-year">{pub["year"]}</span>')
    out.append(f'{i}        </div>')
    out.append(f'{i}        <div class="pub-links">')
    if pub.get("url"):
        out.append(f'{i}            <a href="{esc(pub["url"])}" class="pub-link" target="_blank" rel="noopener">')
        out.append(f'{i}                {ICON % "external-link"} View Article')
        out.append(f'{i}            </a>')
    if pub.get("code_url"):
        out.append(f'{i}            <a href="{esc(pub["code_url"])}" class="pub-link" target="_blank" rel="noopener">')
        out.append(f'{i}                {ICON % "github"} Code')
        out.append(f'{i}            </a>')
    if pub.get("open_access"):
        out.append(f'{i}            <span class="pub-open-access-badge">')
        out.append(f'{i}                {ICON % "unlock-alt"} Open Access')
        out.append(f'{i}            </span>')
    if pub.get("abstract"):
        out.append(
            f'{i}            <button class="expand-btn" type="button" onclick="toggleAbstract(this)"'
            f' aria-expanded="false" aria-label="Show abstract">'
        )
        out.append(f'{i}                {ICON % "plus"}')
        out.append(f'{i}            </button>')
    out.append(f'{i}        </div>')
    if pub.get("abstract"):
        out.append(f'{i}        <div class="pub-abstract" style="display: none;">')
        out.append(f'{i}            <p><strong>Abstract:</strong> {esc(pub["abstract"])}</p>')
        out.append(f'{i}        </div>')
    out.append(f'{i}    </div>')
    out.append(f'{i}</div>')
    return "\n".join(out)


def render_filters(pubs, labels, indent="                            "):
    i = indent
    present = [t for t in labels if any(p["type"] == t for p in pubs)]
    out = [f'{i}<div class="filter-buttons">']
    out.append(
        f'{i}    <button class="filter-btn active" type="button" data-filter="all"'
        f' data-label="All Publications">All Publications</button>'
    )
    for t in present:
        out.append(
            f'{i}    <button class="filter-btn" type="button" data-filter="{esc(t)}"'
            f' data-label="{esc(labels[t])}">{esc(labels[t])}</button>'
        )
    out.append(f'{i}</div>')
    skipped = [t for t in labels if t not in present]
    if skipped:
        print(f"  filters omitted (no entries): {', '.join(skipped)}")
    return "\n".join(out)



def render_software(items, placeholder, indent="                    "):
    """Software entries, or the placeholder paragraph while the list is empty.

    Mirrors render_item()'s structure so a software entry and a publication read
    as the same kind of card: logo where the journal cover goes, then title row,
    description and links.
    """
    i = indent
    if not items:
        return f'{i}<p class="section-placeholder">{esc(placeholder)}</p>'

    out = [f'{i}<div class="software-list">']
    for sw in items:
        has_logo = bool(sw.get("logo"))
        cls = "software-item" if has_logo else "software-item no-logo"
        out.append(f'{i}    <div class="{cls}">')
        if has_logo:
            out.append(f'{i}        <div class="software-logo">')
            out.append(
                f'{i}            <img src="images/software/{esc(sw["logo"])}"'
                f' alt="{esc(sw["name"])} logo" class="software-logo-img"'
                f' width="240" height="186" loading="lazy" decoding="async">'
            )
            out.append(f'{i}        </div>')
        out.append(f'{i}        <div class="software-content">')
        out.append(f'{i}            <div class="software-title-row">')
        out.append(f'{i}                <h3 class="software-name">{esc(sw["name"])}</h3>')
        if sw.get("role") or sw.get("language") or sw.get("license"):
            out.append(f'{i}                <div class="software-chips">')
            # role first: it is the one thing a visitor cannot infer from the repo
            if sw.get("role"):
                out.append(f'{i}                    <span class="software-role">{esc(sw["role"])}</span>')
            if sw.get("language"):
                out.append(f'{i}                    <span class="software-lang">{esc(sw["language"])}</span>')
            if sw.get("license"):
                out.append(f'{i}                    <span class="software-license">{esc(sw["license"])}</span>')
            out.append(f'{i}                </div>')
        out.append(f'{i}            </div>')
        out.append(f'{i}            <p class="software-description">{esc(sw["description"])}</p>')
        out.append(f'{i}            <div class="software-links">')
        out.append(f'{i}                <a href="{esc(sw["url"])}" class="pub-link" target="_blank" rel="noopener">')
        out.append(f'{i}                    {ICON % "github"} Repository')
        out.append(f'{i}                </a>')
        # paper_url is optional: an empty string leaves the slot unrendered
        if sw.get("paper_url"):
            label = sw.get("paper_title") or "Related paper"
            out.append(f'{i}                <a href="{esc(sw["paper_url"])}" class="pub-link" target="_blank" rel="noopener">')
            out.append(f'{i}                    {ICON % "external-link"} {esc(label)}')
            out.append(f'{i}                </a>')
        out.append(f'{i}            </div>')
        out.append(f'{i}        </div>')
        out.append(f'{i}    </div>')
    out.append(f'{i}</div>')
    return "\n".join(out)


def splice(page, start, end, body, what):
    if start not in page or end not in page:
        sys.exit(f"error: {what} markers not found in research.html")
    head = page[: page.index(start) + len(start)]
    tail = page[page.index(end):]
    return head + "\n" + body + "\n" + " " * 20 + tail


def main():
    data = json.loads(PUBS.read_text(encoding="utf-8"))
    pubs = data["publications"]
    labels = data.get("types", {})
    soft = json.loads(SOFT.read_text(encoding="utf-8"))

    # Newest first; the sort buttons re-order client-side from here.
    pubs = sorted(pubs, key=lambda p: (-p["year"], p["title"]))

    page = PAGE.read_text(encoding="utf-8")
    page = splice(page, LIST_START, LIST_END,
                  "\n\n".join(render_item(p) for p in pubs), "publications-list")
    page = splice(page, FILTERS_START, FILTERS_END,
                  render_filters(pubs, labels), "publication-filters")
    page = splice(page, SOFT_START, SOFT_END,
                  render_software(soft.get("software", []), soft.get("placeholder", "")),
                  "software")

    # "Last updated" comes from the data file, so it reflects the last real
    # change to the list rather than the last time this script happened to run.
    updated = esc(data.get("last_updated", ""))
    if UPDATED_START in page:
        head = page[: page.index(UPDATED_START) + len(UPDATED_START)]
        tail = page[page.index(UPDATED_END):]
        page = head + updated + tail

    PAGE.write_text(page, encoding="utf-8")

    by_type = {}
    for p in pubs:
        by_type[p["type"]] = by_type.get(p["type"], 0) + 1
    n_soft = len(soft.get("software", []))
    print(f"wrote {len(pubs)} publications into research.html")
    print("  " + ", ".join(f"{k}: {v}" for k, v in sorted(by_type.items())))
    print(f"  last updated label: {data.get('last_updated')!r}")
    print(f"  software entries: {n_soft}" + ("  (placeholder rendered)" if not n_soft else ""))


if __name__ == "__main__":
    main()
